# -*- coding: utf-8 -*-
"""MusicRecommendation_SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfwRQMZA_Zz3Q6METKX77QG1k2C8J-1S
"""

import pandas as pd

df=pd.read_csv('combined.csv')

df.head(10)

#Drop a database
df = df.drop('Track ID' , axis=1)

df

#Use support vecotr machine
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

X = df.iloc[:, :-1]  # Features (all columns except the last one)
y = df.iloc[:, -1]   # Target variable (last column)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the SVM model
clf = SVC(kernel='linear')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print('Accuracy:', accuracy)